services:
  totalagilityapi:
    image: ${DOCKER_REGISTRY-}totalagilityapi
    build:
      context: TotalAgilityApi
      dockerfile: Dockerfile
    container_name: total_agility_api
    ports:
      - "8080:8080"
      - "8081:8081"

  prometheus:
    image: prom/prometheus:latest
    container_name: total_agility_prometheus
    volumes:
      - ./TotalAgilityApi/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090" 
